project:
  type: website

website:
  title: "Statistique en grande dimension"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Clement-Poupelin
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

