project:
  type: website
  output-dir: docs

theme:
  dark: darkly
  light: zephir
  
website:
  title: Statistique en grande dimension
  site-url: https://clement-poupelin.github.io/Statistique_en_grande_dimension/
  favicon: img/logo_univ_nantes_simple.png
  navbar:
    background: light
    title: X3MS020
    logo: img/logo_univ_nantes_complet.png
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Clement-Poupelin
      - icon: linkedin
        href: http://www.linkedin.com/in/cl%C3%A9ment-poupelin-7675311a7/
      - icon: envelope
        href: mailto:clementjc.poupelin@gmail.com
      - icon: instagram
        href: https://www.instagram.com/clement__poupelin
  page-footer: 
    background: light
    left: Copyright 2025, Clément Poupelin
    right: This blog is built with [Quarto](https://quarto.org/)


format:
  html:
    toc: true
    
editor: visual